services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: gradeup_back
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./src:/var/www
    networks:
      - gradeup
    command: php-fpm
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: gradeup_worker
    env_file:
      - src/.env
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./src:/var/www
    networks:
      - gradeup
    command: php artisan horizon
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:7-alpine
    container_name: gradeup_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gradeup
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: gradeup_nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - gradeup

  postgres:
    image: postgres:18-alpine
    container_name: gradeup_postgres
    environment:
      POSTGRES_DB: gradeup
      POSTGRES_USER: gradeup
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gradeup
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U gradeup -d gradeup" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  mailhog:
    image: mailhog/mailhog
    container_name: gradeup_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - gradeup
    restart: unless-stopped

volumes:
  postgres_data:
    name: gradeup_postgres_data
  redis_data:
    name: gradeup_redis_data

networks:
  gradeup:
    driver: bridge
